FROM node:14

WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn

# Copy files

ADD ./src/database/migrations ./src/database/migrations
ADD ./tsconfig.json ./tsconfig.json

CMD yarn dev
