/**
 * You need to create a migration to update the enum on the database too!
 */
export enum SectionTypeEnum {
	PERSONAL_INFORMATION = "PERSONAL_INFORMATION",
	SALARY_EXPECTATION = "SALARY_EXPECTATION",
	LOCATION = "LOCATION",
	LANGUAGES = "LANGUAGES",
	SKILLS = "SKILLS",
	PORTFOLIO = "PORTFOLIO",
	OPEN_SOURCES = "OPEN_SOURCES",
	EMPLOYMENTS = "EMPLOYMENTS",
	ORGANIZATIONS = "ORGANIZATIONS",
	EDUCATIONS = "EDUCATIONS",
}
